TRUNCATE TABLE BANK;
DROP TABLE BANK;
CREATE TABLE BANK(ACC_NO NUMBER(6) PRIMARY KEY,
                    USER_NAME VARCHAR2(10) UNIQUE,
                    AUTH_PIN VARCHAR2(4), 
                    BALANCE NUMBER(10,2) DEFAULT 0);

SELECT * FROM BANK;